trajectory_planner:
  ros__parameters:
    map_topic: "/map"
    scan_topic: "/scan"
    odom_topic: "/pf/pose/odom"

trajectory_follower:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/vesc/input/navigation"

safety_stop:
  ros__parameters:
    velocity: 1.0
